name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Get branch
        id: get_branch
        run: echo ::set-output name=GITHUB_BRANCH::${GITHUB_REF/refs\/heads\//}

      - name: Update images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          make ci_doc
        env:
          GITHUB_BRANCH: ${{ steps.get_branch.outputs.GITHUB_BRANCH }}

      - name: Test
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
